version: '3'

services:
  frontend:
    image: frontend:latest
    container_name: smart_lugar_frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    image: backend:latest
    container_name: smart_lugar_backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"