# Use a Node.js base image
FROM arm32v7/node:17

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY backend/package*.json ./

# Copy the shared folder
COPY shared ../shared

# Install dependencies
RUN npm ci

# Copy the rest of the application
COPY backend/ .

# Build the project
RUN npm run build

# Expose port 3000
EXPOSE 3000

# Start the backend server
CMD ["npm", "run", "start:prod"]