name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push Frontend Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend -f Dockerfile.frontend .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend

      - name: Build and Push Backend Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/backend -f Dockerfile.backend .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend
